name = "Raijin"
uuid = "3357f91b-de77-4f4c-9e57-c9a6bea0fb7b"
authors = ["Martí Circuns Duxans"]
version = "1.0.0-DEV"

[compat]
julia = "1.6.7"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
